### ISSUE TITLE
Change all instances of GoPhish to Gophish

### ISSUE THREAD

**Issue by JCantu248** [cisagov/gophish-tools#35]
# 💡 Summary #

Anywhere in the gophish-tools repository where there is an instance or reference to GoPhish, change it to Gophish
## Motivation and context ##

Why does this work belong in this project?

This would keep the naming convention in line with other CISAGov projects using Gophish.

## Acceptance criteria ##

How do we know when this work is done?

- [x] All instances and references to GoPhish are changed to Gophish
- [x]  Gophish-tools still works as expected

**Comment by ameliav** [comment]
https://github.com/cisagov/gophish-tools/pull/50 created for this issue
