### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by iblissguy** [cisagov/gophish-tools#64]
# 🐛 Summary #

What's wrong? Please be specific.

I downloaded "gophish_export.py" and then when i try to run "python gophish_export.py" i get the following answer: 

"# python gophish_export.py
  File "gophish_export.py", line 161
    rawCampaign: dict = api.campaigns.get(campaign_id).as_dict()
               ^
SyntaxError: invalid syntax "

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

I want to export my gophish config to JSON and backup them up

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by mcdonnnj** [comment]
@iblissguy We would need more information about your environment to assist you. Things such as OS, Python version, etc. Also this is a Python package and I see that you are not installing it as such.

**Comment by iblissguy** [comment]
i missunderstood how to use the feature. After some time taking pain in here, i got it... now im struggling with the assessment id thing
